In [1]:
import pandas as pd

In [2]:
player_df_final = pd.read_csv('player_data_final.csv')

In [3]:
player_df_final.head()

,ID,player,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
0,1,player1,1893.0,1251.8,97.8,63.0,33.9,0.569,17.2,11.5,26.1,4.7,23.3,7.8,10.900000
1,2,player2,1386.0,1282.5,110.5,58.0,32.5,0.511,24.8,9.7,26.9,6.1,0.9,10.7,27.300000
2,3,player3,1405.0,1252.3,105.8,55.0,36.3,0.605,25.7,13.9,28.1,4.5,4.9,1.8,16.595759
3,4,player4,1282.0,1235.9,100.7,54.0,37.6,0.636,29.5,11.0,22.3,4.8,4.6,5.6,22.350000
4,5,player5,1721.0,1254.0,105.7,59.0,30.5,0.589,22.8,9.9,24.6,1.2,8.4,12.1,28.380000

In [6]:
ts_df = player_df_final.iloc[26: , :]
ts_df.head()

,ID,player,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
26,31,tune_squad1,2049.0,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000
27,32,tune_squad2,1795.0,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000
28,33,tune_squad3,1805.0,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000
29,34,tune_squad4,1743.0,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.853138
30,35,tune_squad5,1963.0,1539.1,117.4,59.771429,35.208333,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000

In [7]:
ts_df.tail()

,ID,player,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
36,42,tune_squad12,1631.0,1465.7,110.1,66.000000,37.5,0.613,28.4,14.4,35.7,6.5,20.7,14.0,28.40000
37,43,tune_squad13,1828.0,1507.2,112.7,64.000000,36.5,0.618,31.3,14.0,34.9,5.9,21.3,14.5,29.09431
38,44,tune_squad14,1821.0,1443.7,118.8,66.000000,36.6,0.609,27.3,13.5,35.8,7.0,23.8,11.5,22.96000
39,45,tune_squad15,1740.0,1443.9,114.1,68.000000,37.1,0.611,26.6,15.2,29.3,8.3,17.7,11.1,21.22000
40,46,tune_squad16,1993.0,1459.0,112.5,59.771429,36.9,0.627,30.4,15.0,33.7,6.3,19.3,14.1,28.76000

- ID: A unique identifier for each player in the dataset
- player: A unique identifer created to track which player is a Tune Squad player versus a human
- points: Total points scored by a player in a season
- possessions: Total possessions by a player in a season
- team_pace: Average number of possessions a team uses per game
- GP: Games played by a player in a season
- MPG: Average minutes played by a player per game
- TS%: True shooting percentage, a player's shooting percentage, taking free throws and three-pointers into account
- AST: Assist ratio, the percentage of a player's possessions that end in an assist
- TO: Turnover ratio, the percentage of a player's possessions that end in a turnover
- USG: Usage rate, the number of possessions a player uses per 40 minutes
- ORR: Offensive rebound rate
- DRR: Defensive rebound rate
- REBR: Rebound rate, the percentage of missed shots that a player rebounds
- PER: Player efficiency rating, a measure of a player's per-minute productivity on the court

In [9]:
ts_name_df = pd.read_csv('tune_squad.csv', sep='\t')
ts_name_df

    ID              player
0   31           Sylvester
1   32  Marvin the Martian
2   33         Road Runner
3   34     Foghorn Leghorn
4   35          Bugs Bunny
5   36          Elmer Fudd
6   37          Lola Bunny
7   38           Porky Pig
8   39     Tasmanian Devil
9   40        Yosemite Sam
10  41            Gossamer
11  42              Granny
12  43      Wile E. Coyote
13  44              Tweety
14  45            Penelope
15  46          Daffy Duck

In [10]:
# Merge the two DataFrames.
ts_df = pd.merge(ts_df, ts_name_df, on='ID', how='left', suffixes=('_type', '_name'))
ts_df.head()

,ID,player_type,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER,player_name
0,31,tune_squad1,2049.0,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000,Sylvester
1,32,tune_squad2,1795.0,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000,Marvin the Martian
2,33,tune_squad3,1805.0,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000,Road Runner
3,34,tune_squad4,1743.0,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.853138,Foghorn Leghorn
4,35,tune_squad5,1963.0,1539.1,117.4,59.771429,35.208333,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000,Bugs Bunny

- Create a list of the columns.
- Remove the player_name column from the list (we know it's at the end, so we can simply drop it off the list).
- Put player_name in the second position of the column list, replacing the player_type column.
- Set our DataFrame to the new arrangement of columns.

In [11]:
# Rearrange the columns to put the ID and player_name columns next to each other.
column_list = list(ts_df)

player_name = column_list.pop()
column_list[1] = player_name

ts_df = ts_df[column_list]
ts_df.head()

,ID,player_name,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
0,31,Sylvester,2049.0,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000
1,32,Marvin the Martian,1795.0,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000
2,33,Road Runner,1805.0,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000
3,34,Foghorn Leghorn,1743.0,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.853138
4,35,Bugs Bunny,1963.0,1539.1,117.4,59.771429,35.208333,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000

- TS%: A player's shooting percentage, taking free throws and three-pointers into account
- AST: The percentage of a player's possessions that end in an assist
- TO: The percentage of a player's possessions that end in a turnover
- USG: The number of possessions a player uses per 40 minutes
- ORR: The player's offensive rebound rate
- DRR: The player's defensive rebound rate
- REBR: The percentage of missed shots that a player rebounds

In [13]:
# Create a list of only the column names we're interested in.
game_stat_cols = list(ts_df.iloc[:, 7:-1])
game_stat_stdevs = []

for col in game_stat_cols:
    game_stat_stdevs.append(ts_df[col].std())

# Create a Series of the standard deviations, with the stat names as the index.
stdev_s = pd.Series(game_stat_stdevs, index=game_stat_cols)
stdev_s

TS%     0.008262
AST     2.140494
TO      0.797197
USG     1.892718
ORR     1.139465
DRR     3.017962
REBR    1.802564
dtype: float64

In [14]:
# Import the models and libraries we need.
from sklearn.linear_model import LinearRegression
from numpy.random import randn

# Get the dependent and independent variables for modeling the PER.
X = player_df_final.iloc[:, 7:-1].to_numpy()
y = player_df_final.iloc[:, -1]

In [16]:
lin_reg = LinearRegression()
lin_reg.fit(X, y)

LinearRegression()

- Create an empty DataFrame that contains only the player's names.
- For each stat for that player, generate a random number within the standard deviation for that player for that stat.
- Save that randomly generated number in the DataFrame.
- Predict the PER for each player based on the new DataFrame of randomly generated numbers.
- Print each iteration, with the lowest PER player and the highest PER player.

In [18]:
# Print the player with the highest and lower PER for each iteration. (/t tabulator)
print('Iteration # \thigh PER \tlow PER')

# Run the simulation 10 times.
for i in range(10):

    # Define an empty temporary DataFrame for each iteration.
    # The columns of this DataFrame are the player stats and the index is the players' names.
    game_df = pd.DataFrame(columns=game_stat_cols, index=list(ts_df['player_name']))
    
    # Loop through each stat.
    for stat in game_stat_cols:
        
        # Each player's stats are used to generate a random value for each iteration.
        game_df[stat] = list(ts_df[stat] + randn(len(ts_df)) * stdev_s[stat])
    
    # Use the fitted model to predict players' PERs based on the randomized data.
    game_df['PER'] = lin_reg.predict(game_df)

    # Print the player with the highest and lower PER for each iteration.
    print('Iteration {}'.format(i+1) + ' \t' + game_df['PER'].idxmax() + ' \t' + game_df['PER'].idxmin())

Iteration # 	high PER 	low PER
Iteration 1 	Lola Bunny 	Road Runner
Iteration 2 	Lola Bunny 	Penelope
Iteration 3 	Foghorn Leghorn 	Penelope
Iteration 4 	Gossamer 	Tasmanian Devil
Iteration 5 	Lola Bunny 	Tasmanian Devil
Iteration 6 	Lola Bunny 	Marvin the Martian
Iteration 7 	Porky Pig 	Tasmanian Devil
Iteration 8 	Gossamer 	Porky Pig
Iteration 9 	Lola Bunny 	Tasmanian Devil
Iteration 10 	Gossamer 	Tasmanian Devil

C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [19]:
# Initialize four empty DataFrames, one for each 12-minute period.
number_of_iterations = 4
df_list = [pd.DataFrame(columns=game_stat_cols, index=list(ts_df['player_name'])) for i in range(number_of_iterations)]

# For each period, generate randomized player data and predict the PER.
# Use the model fitted earlier.
for df in df_list:
    for stat in game_stat_cols:
        df[stat] = list(ts_df[stat] + randn(len(ts_df)) * stdev_s[stat])
    df['PER'] = lin_reg.predict(df)

# Concatenate the DataFrames and make the players' names the index.
game_df = pd.concat(df_list)
game_df.rename_axis('player_name', inplace=True)

# Create another index for the period in question.
minutes = [(x // len(ts_df)) * 12 for x in range(len(game_df))]
game_df['minutes'] = minutes
game_df.set_index('minutes', append=True, inplace=True)
game_df = game_df.swaplevel()

game_df

C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\staros1\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

                                 TS%        AST         TO        USG  \
minutes player_name
0       Sylvester           0.621717  31.159455  14.182777  36.615743
        Marvin the Martian  0.610850  33.379664  15.021067  30.819698
        Road Runner         0.636998  28.984069  14.471600  37.915536
        Foghorn Leghorn     0.618496  29.328788  14.799123  33.086371
        Bugs Bunny          0.621907  31.768569  15.125170  36.301479
        Elmer Fudd          0.627121  30.783529  15.399157  34.823551
        Lola Bunny          0.650445  31.935453  14.753089  38.578089
        Porky Pig           0.604912  30.551678  16.997275  33.780043
        Tasmanian Devil     0.606399  30.591015  15.515317  37.287889
        Gossamer            0.623755  29.825105  16.019144  36.206801
        Granny              0.606413  26.942520  14.889594  34.738014
        Wile E. Coyote      0.631225  28.210316  12.477504  34.715915
        Tweety              0.610486  31.726837  14.450928  34.497037
        Penelope            0.617551  27.348022  15.435885  28.252267
        Daffy Duck          0.640924  30.008645  13.610686  33.109390
12      Sylvester           0.625411  28.603912  15.342206  37.317826
        Marvin the Martian  0.604801  30.875479  16.011058  30.619157
        Road Runner         0.611518  27.606214  13.635430  38.985903
        Foghorn Leghorn     0.621184  30.277381  16.499196  32.892858
        Bugs Bunny          0.628564  33.974200  14.771874  35.281936
        Elmer Fudd          0.631537  30.465925  15.597717  37.138775
        Lola Bunny          0.630283  33.239051  14.091646  38.528867
        Porky Pig           0.603137  30.353029  15.195003  36.934534
        Tasmanian Devil     0.607712  23.630956  15.518450  33.564897
        Gossamer            0.626504  30.410165  15.932377  32.417661
        Granny              0.591986  25.689949  12.872577  37.869172
        Wile E. Coyote      0.612111  29.227427  13.036547  33.063664
        Tweety              0.612988  26.606133  14.134758  37.891912
        Penelope            0.611928  22.856339  14.153636  30.482245
        Daffy Duck          0.635816  26.269223  15.114565  32.200384
24      Sylvester           0.614649  30.922313  13.251238  37.976637
        Marvin the Martian  0.599159  32.067529  14.251189  34.149061
        Road Runner         0.619189  30.731085  14.338393  32.847789
        Foghorn Leghorn     0.616495  31.491719  15.489901  34.163000
        Bugs Bunny          0.630555  37.086260  15.777538  36.076501
        Elmer Fudd          0.619990  29.439635  13.963678  34.542481
        Lola Bunny          0.639748  31.159047  14.025163  40.611184
        Porky Pig           0.629930  28.302658  14.526425  37.647867
        Tasmanian Devil     0.614580  28.904403  13.627627  38.440046
        Gossamer            0.620637  32.105067  15.326928  31.082724
        Granny              0.617187  31.560213  14.869651  33.293198
        Wile E. Coyote      0.613187  27.942228  14.191886  36.003991
        Tweety              0.613149  29.801313  13.495496  36.835412
        Penelope            0.598890  28.694660  15.023926  31.167339
        Daffy Duck          0.630592  33.478217  13.359772  35.532335
36      Sylvester           0.617360  34.993418  15.368062  37.236539
        Marvin the Martian  0.609899  30.141742  12.808885  32.991177
        Road Runner         0.624153  32.219962  14.804408  37.100262
        Foghorn Leghorn     0.627722  30.229929  16.543564  35.816816
        Bugs Bunny          0.621622  30.504183  16.923818  28.860220
        Elmer Fudd          0.628075  30.999542  16.759639  35.055942
        Lola Bunny          0.629983  34.036432  13.642318  37.510226
        Porky Pig           0.610330  28.604887  14.770193  36.571754
        Tasmanian Devil     0.607764  27.865485  15.514656  35.278615
        Gossamer            0.636973  29.890278  14.476776  37.087953
        Granny              0.614744  27.068059  15.567566  35.318753
        Wile E. Coyote      0.632988  34.743651  15.188188  32.635130
        Tweety              0.598859  28.786931  14.018364  37.487056
        Penelope            0.607120  29.839655  15.889598  31.343647
        Daffy Duck          0.638954  32.301805  16.585224  37.662844

                                 ORR        DRR       REBR        PER
minutes player_name
0       Sylvester           9.606137  18.381261  12.967290  28.939839
        Marvin the Martian  6.596080  23.755342  11.853356  20.481763
        Road Runner         4.664894  30.451483  12.581269  23.441942
        Foghorn Leghorn     5.249714  19.211873  13.432106  27.343853
        Bugs Bunny          5.751041  19.217729  12.829741  28.556991
        Elmer Fudd          5.798075  29.319685  14.469161  23.725618
        Lola Bunny          4.969191  27.076381  20.433038  37.651662
        Porky Pig           4.827168  23.838513  13.190062  22.787656
        Tasmanian Devil     5.409629  30.520955   8.893923  15.552517
        Gossamer            5.517334  19.519792  11.900631  26.499056
        Granny              6.110091  19.743991  12.805305  25.944331
        Wile E. Coyote      5.916099  18.245009  12.986128  30.038610
        Tweety              7.366465  16.195400  11.041441  26.180805
        Penelope            7.993655  19.843504   9.416578  17.191440
        Daffy Duck          8.052532  20.366914  13.381282  27.873110
12      Sylvester           7.221934  10.872838  11.591805  32.014960
        Marvin the Martian  5.472124  18.868846  12.870225  23.940833
        Road Runner         6.091582  26.294810  11.923704  24.265354
        Foghorn Leghorn     6.202888  19.894560  15.813449  29.172201
        Bugs Bunny          4.281815  16.703447   9.920105  26.626330
        Elmer Fudd          5.379622  22.949621  14.375338  29.143043
        Lola Bunny          4.370384  19.614644  14.989193  34.185939
        Porky Pig           4.179149  14.018745  14.881112  34.151723
        Tasmanian Devil     5.191163  17.659068   7.618045  18.962017
        Gossamer            7.211664  17.970705  12.095605  25.296597
        Granny              5.371492  28.924517  14.561128  24.932623
        Wile E. Coyote      8.431979  19.627515  17.638018  32.718718
        Tweety              5.535428  20.555162   6.311099  19.221982
        Penelope            8.495614  20.397940  11.092041  20.334500
        Daffy Duck          7.870111  15.255313  14.528424  30.638056
24      Sylvester           8.607940  22.634453  13.179427  27.757649
        Marvin the Martian  5.817476  24.292975  14.289283  25.353001
        Road Runner         7.133932  29.173408  12.040090  19.058627
        Foghorn Leghorn     6.066118  19.704525  15.707430  30.351610
        Bugs Bunny          5.251071  19.402775  14.474816  31.369343
        Elmer Fudd          2.488689  28.480939  13.883949  24.355371
        Lola Bunny          3.693294  27.754008  17.184521  33.980055
        Porky Pig           5.567200  16.298601  14.027584  33.329615
        Tasmanian Devil     6.422395  21.123011   9.220707  23.613424
        Gossamer            4.439028  17.883891  15.474045  30.105657
        Granny              8.203218  19.101811  12.794061  26.014456
        Wile E. Coyote      4.770046  24.650798  14.574224  27.327138
        Tweety              6.367495  24.337793  11.314483  23.661197
        Penelope            9.087071  21.536199  13.539051  22.635597
        Daffy Duck          7.405694  18.993615  11.539047  27.672690
36      Sylvester           7.618226  14.816049  11.558795  29.533857
        Marvin the Martian  6.000131  19.307836   8.333323  20.658588
        Road Runner         5.366876  28.239930  14.256578  25.874406
        Foghorn Leghorn     5.694165  19.622190  17.780732  34.293840
        Bugs Bunny          6.967998  16.596225  17.495258  30.753305
        Elmer Fudd          5.108393  18.105156  14.042643  29.711718
        Lola Bunny          5.017923  20.345751  15.181716  33.538787
        Porky Pig           5.405133  20.977327  14.684857  29.517708
        Tasmanian Devil     4.549202  20.504512   9.449248  21.350517
        Gossamer            7.459300  12.092070  16.524467  39.175723
        Granny              5.217512  17.671212  17.495342  34.420219
        Wile E. Coyote      7.858883  17.531948  12.795740  27.717373
        Tweety              6.295438  24.833761  13.184870  25.154209
        Penelope            6.951559  14.831219  11.658541  24.920353
        Daffy Duck          8.472592  18.395540  16.023146  33.842580

In [20]:
# Export the finished DataFrame to CSV.
game_df.to_csv('game_stats.csv')